name: CI

on: [push, pull_request]

jobs:
  build:
    name: build

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install dependencies
        run: npm install

      - name: Review eslint
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          eslint_flags: './**/*.{ts,js}'

      - name: Run eslint
        run: npm run lint

      - name: Run build
        run: npm run compile

      - name: Run test
        uses: GabrielBB/xvfb-action@v1
        with:
          run: npm test
